# $Id: Makefile,v 1.2 2011/07/24 16:18:01 ferber Exp $

# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.PHONY: all clean

all:
	$(SHELL) ./doit.sh

clean:
	$(RM) _user.pdf
	$(RM) _print.{ps,pdf}
	$(RM) _quer.pdf
	$(RM) *~

# eof
